In [9]:
import requests
from bs4 import BeautifulSoup

url = 'https://www.worldometers.info/coronavirus/'
html = requests.get(url).content
soup = BeautifulSoup(html, "lxml")

In [6]:
# tags = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'h7', 'p']
# soup.find_all(tags)
# text = [element.text for element in ]
# text

bs4.element.Tag

In [14]:
cdict = {'class':'resultsarchive-table'}
iddict = {'id':'main_table_countries_today'}

table = soup.find_all('table',iddict)[0]
table

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>1,985,494</td>
<td>+4,307</td>
<td>120,654</td>
<td>+480</td>
<td>624,697</td>
<td>+2,396</td>
<td>1,240,143</td>
<td>19,456</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>758,107</td>
<td>+619</td>
<td>36,746</td>
<td>+13</td>
<td>320,826</td>
<td>+49</td>
<td>400,535</td>
<td>11,077</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>1,982,048</td>
<td>+12,149</td>
<td>172,017</td>
<td>+449</td>
<td>960,087</td>
<td>+11,591</td>
<td>849,944</td>
<td>9,354</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>1,069,380</td>
<td>+18,114</td>
<td>29,399</td>
<td>+279</td>
<td>635,449</td>
<td>+13,705</td>
<td>404,532</td>
<td>13,704</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>132,668</td>
<td>+1,081</td>
<td>3,820</td>
<td>+6</td>
<td>55,300</td>
<td>+174</td>
<td>73,548</td>
<td>355</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>8,782</td>
<td>+23</td>
<td>125</td>
<td></td>
<td>8,164</td>
<td>+9</td>
<td>493</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>651</td>
<td></td>
<td>55</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>5,937,200</td>
<td>+36,293</td>
<td>362,776</td>
<td>+1,227</td>
<td>2,605,174</td>
<td>+27,924</td>
<td>2,969,250</td>
<td>53,954</td>
<td>762</td>
<td>46.5</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">1,768,868</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+407</td>
<td style="font-weight: bold; text-align:right;">103,345 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+15</td>
<td style="font-weight: bold; text-align:right">498,762</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+37</td>
<td style="text-align:right;font-weight:bold;">1,166,761</td>
<td style="font-weight: bold; text-align:right">17,202</td>
<td style="font-weight: bold; text-align:right">5,347</td>
<td style="font-weight: bold; text-align:right">312</td>
<td style="font-weight: bold; text-align:right">16,333,027</td>
<td style="font-weight: bold; text-align:right">49,370</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">330,827,597</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>187</td><td>3,201</td><td>20</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">438,812</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">26,764 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">193,181</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">218,867</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">2,066</td>
<td style="font-weight: bold; text-align:right">126</td>
<td style="font-weight: bold; text-align:right">871,839</td>
<td style="font-weight: bold; text-align:right">4,104</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">212,422,152</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>484</td><td>7,937</td><td>244</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">387,623</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+8,572</td>
<td style="font-weight: bold; text-align:right;">4,374 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+232</td>
<td style="font-weight: bold; text-align:right">159,257</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+8,264</td>
<td style="text-align:right;font-weight:bold;">223,992</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">2,656</td>
<td style="font-weight: bold; text-align:right">30</td>
<td style="font-weight: bold; text-align:right">10,000,061</td>
<td style="font-weight: bold; text-align:right">68,527</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,928,996</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>376</td><td>33,363</td><td>15</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">284,986</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">27,119 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">196,958</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">60,909</td>
<td style="font-weight: bold; text-align:right">854</td>
<td style="font-weight: bold; text-align:right">6,096</td>
<td style="font-weight: bold; text-align:right">580</td>
<td style="font-weight: bold; text-align:right">3,556,567</td>
<td style="font-weight: bold; text-align:right">76,071</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,753,197</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>164</td><td>1,724</td><td>13</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">269,127</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">37,837 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">1,559</td>
<td style="font-weight: bold; text-align:right">3,966</td>
<td style="font-weight: bold; text-align:right">558</td>
<td style="font-weight: bold; text-align:right">3,918,079</td>
<td style="font-weight: bold; text-align:right">57,743</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">67,853,964</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>252</td><td>1,793</td><td>17</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">231,732</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">33,142 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">150,604</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">47,986</td>
<td style="font-weight: bold; text-align:right">489</td>
<td style="font-weight: bold; text-align:right">3,832</td>
<td style="font-weight: bold; text-align:right">548</td>
<td style="font-weight: bold; text-align:right">3,683,144</td>
<td style="font-weight: bold; text-align:right">60,909</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,469,504</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>261</td><td>1,825</td><td>16</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">186,238</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">28,662 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">67,191</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">90,385</td>
<td style="font-weight: bold; text-align:right">1,429</td>
<td style="font-weight: bold; text-align:right">2,854</td>
<td style="font-weight: bold; text-align:right">439</td>
<td style="font-weight: bold; text-align:right">1,384,633</td>
<td style="font-weight: bold; text-align:right">21,217</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,260,761</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>350</td><td>2,277</td><td>47</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">182,495</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+43</td>
<td style="font-weight: bold; text-align:right;">8,574 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+4</td>
<td style="font-weight: bold; text-align:right">164,100</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+900</td>
<td style="text-align:right;font-weight:bold;">9,821</td>
<td style="font-weight: bold; text-align:right">744</td>
<td style="font-weight: bold; text-align:right">2,179</td>
<td style="font-weight: bold; text-align:right">102</td>
<td style="font-weight: bold; text-align:right">3,952,971</td>
<td style="font-weight: bold; text-align:right">47,194</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,760,156</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>459</td><td>9,769</td><td>21</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">167,451</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,065</td>
<td style="font-weight: bold; text-align:right;">4,797 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+86</td>
<td style="font-weight: bold; text-align:right">71,410</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+490</td>
<td style="text-align:right;font-weight:bold;">91,244</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">121</td>
<td style="font-weight: bold; text-align:right">3</td>
<td style="font-weight: bold; text-align:right">3,483,838</td>
<td style="font-weight: bold; text-align:right">2,527</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,378,752,175</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>8,234</td><td>287,420</td><td>396</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">160,979</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">4,461 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">124,369</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">32,149</td>
<td style="font-weight: bold; text-align:right">683</td>
<td style="font-weight: bold; text-align:right">1,911</td>
<td style="font-weight: bold; text-align:right">53</td>
<td style="font-weight: bold; text-align:right">1,928,209</td>
<td style="font-weight: bold; text-align:right">22,885</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">84,254,857</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>523</td><td>18,887</td><td>44</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
<td style="font-weight: bold; text-align:right">146,668</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,819</td>
<td style="font-weight: bold; text-align:right;">7,677 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+50</td>
<td style="font-weight: bold; text-align:right">114,931</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,943</td>
<td style="text-align:right;font-weight:bold;">24,060</td>
<td style="font-weight: bold; text-align:right">2,547</td>
<td style="font-weight: bold; text-align:right">1,748</td>
<td style="font-weight: bold; text-align:right">92</td>
<td style="font-weight: bold; text-align:right">896,571</td>
<td style="font-weight: bold; text-align:right">10,687</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/iran-population/">83,892,015</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>572</td><td>10,928</td><td>94</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
<td style="font-weight: bold; text-align:right">141,779</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">4,099 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">59,442</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">78,238</td>
<td style="font-weight: bold; text-align:right">926</td>
<td style="font-weight: bold; text-align:right">4,306</td>
<td style="font-weight: bold; text-align:right">124</td>
<td style="font-weight: bold; text-align:right">928,797</td>
<td style="font-weight: bold; text-align:right">28,207</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">32,928,451</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>232</td><td>8,033</td><td>35</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/canada/">Canada</a></td>
<td style="font-weight: bold; text-align:right">88,512</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">6,877 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">46,840</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">34,795</td>
<td style="font-weight: bold; text-align:right">1,613</td>
<td style="font-weight: bold; text-align:right">2,347</td>
<td style="font-weight: bold; text-align:right">182</td>
<td style="font-weight: bold; text-align:right">1,585,235</td>
<td style="font-weight: bold; text-align:right">42,036</td>

In [22]:
tags = ['thead','tbody']
tableparts = table.find_all(tags)
thead = tableparts[0]
tbody = tableparts[1]
tbody

<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>1,985,494</td>
<td>+4,307</td>
<td>120,654</td>
<td>+480</td>
<td>624,697</td>
<td>+2,396</td>
<td>1,240,143</td>
<td>19,456</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>758,107</td>
<td>+619</td>
<td>36,746</td>
<td>+13</td>
<td>320,826</td>
<td>+49</td>
<td>400,535</td>
<td>11,077</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>1,982,048</td>
<td>+12,149</td>
<td>172,017</td>
<td>+449</td>
<td>960,087</td>
<td>+11,591</td>
<td>849,944</td>
<td>9,354</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>1,069,380</td>
<td>+18,114</td>
<td>29,399</td>
<td>+279</td>
<td>635,449</td>
<td>+13,705</td>
<td>404,532</td>
<td>13,704</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>132,668</td>
<td>+1,081</td>
<td>3,820</td>
<td>+6</td>
<td>55,300</td>
<td>+174</td>
<td>73,548</td>
<td>355</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>8,782</td>
<td>+23</td>
<td>125</td>
<td></td>
<td>8,164</td>
<td>+9</td>
<td>493</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>651</td>
<td></td>
<td>55</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>5,937,200</td>
<td>+36,293</td>
<td>362,776</td>
<td>+1,227</td>
<td>2,605,174</td>
<td>+27,924</td>
<td>2,969,250</td>
<td>53,954</td>
<td>762</td>
<td>46.5</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">1,768,868</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+407</td>
<td style="font-weight: bold; text-align:right;">103,345 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+15</td>
<td style="font-weight: bold; text-align:right">498,762</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+37</td>
<td style="text-align:right;font-weight:bold;">1,166,761</td>
<td style="font-weight: bold; text-align:right">17,202</td>
<td style="font-weight: bold; text-align:right">5,347</td>
<td style="font-weight: bold; text-align:right">312</td>
<td style="font-weight: bold; text-align:right">16,333,027</td>
<td style="font-weight: bold; text-align:right">49,370</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">330,827,597</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>187</td><td>3,201</td><td>20</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">438,812</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">26,764 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">193,181</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">218,867</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">2,066</td>
<td style="font-weight: bold; text-align:right">126</td>
<td style="font-weight: bold; text-align:right">871,839</td>
<td style="font-weight: bold; text-align:right">4,104</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">212,422,152</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>484</td><td>7,937</td><td>244</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">387,623</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+8,572</td>
<td style="font-weight: bold; text-align:right;">4,374 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+232</td>
<td style="font-weight: bold; text-align:right">159,257</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+8,264</td>
<td style="text-align:right;font-weight:bold;">223,992</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">2,656</td>
<td style="font-weight: bold; text-align:right">30</td>
<td style="font-weight: bold; text-align:right">10,000,061</td>
<td style="font-weight: bold; text-align:right">68,527</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,928,996</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>376</td><td>33,363</td><td>15</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">284,986</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">27,119 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">196,958</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">60,909</td>
<td style="font-weight: bold; text-align:right">854</td>
<td style="font-weight: bold; text-align:right">6,096</td>
<td style="font-weight: bold; text-align:right">580</td>
<td style="font-weight: bold; text-align:right">3,556,567</td>
<td style="font-weight: bold; text-align:right">76,071</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,753,197</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>164</td><td>1,724</td><td>13</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">269,127</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">37,837 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">1,559</td>
<td style="font-weight: bold; text-align:right">3,966</td>
<td style="font-weight: bold; text-align:right">558</td>
<td style="font-weight: bold; text-align:right">3,918,079</td>
<td style="font-weight: bold; text-align:right">57,743</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">67,853,964</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>252</td><td>1,793</td><td>17</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">231,732</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">33,142 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">150,604</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">47,986</td>
<td style="font-weight: bold; text-align:right">489</td>
<td style="font-weight: bold; text-align:right">3,832</td>
<td style="font-weight: bold; text-align:right">548</td>
<td style="font-weight: bold; text-align:right">3,683,144</td>
<td style="font-weight: bold; text-align:right">60,909</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,469,504</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>261</td><td>1,825</td><td>16</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">186,238</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">28,662 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">67,191</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">90,385</td>
<td style="font-weight: bold; text-align:right">1,429</td>
<td style="font-weight: bold; text-align:right">2,854</td>
<td style="font-weight: bold; text-align:right">439</td>
<td style="font-weight: bold; text-align:right">1,384,633</td>
<td style="font-weight: bold; text-align:right">21,217</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,260,761</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>350</td><td>2,277</td><td>47</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">182,495</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+43</td>
<td style="font-weight: bold; text-align:right;">8,574 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+4</td>
<td style="font-weight: bold; text-align:right">164,100</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+900</td>
<td style="text-align:right;font-weight:bold;">9,821</td>
<td style="font-weight: bold; text-align:right">744</td>
<td style="font-weight: bold; text-align:right">2,179</td>
<td style="font-weight: bold; text-align:right">102</td>
<td style="font-weight: bold; text-align:right">3,952,971</td>
<td style="font-weight: bold; text-align:right">47,194</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,760,156</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>459</td><td>9,769</td><td>21</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">167,451</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,065</td>
<td style="font-weight: bold; text-align:right;">4,797 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+86</td>
<td style="font-weight: bold; text-align:right">71,410</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+490</td>
<td style="text-align:right;font-weight:bold;">91,244</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">121</td>
<td style="font-weight: bold; text-align:right">3</td>
<td style="font-weight: bold; text-align:right">3,483,838</td>
<td style="font-weight: bold; text-align:right">2,527</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,378,752,175</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>8,234</td><td>287,420</td><td>396</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">160,979</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">4,461 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">124,369</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">32,149</td>
<td style="font-weight: bold; text-align:right">683</td>
<td style="font-weight: bold; text-align:right">1,911</td>
<td style="font-weight: bold; text-align:right">53</td>
<td style="font-weight: bold; text-align:right">1,928,209</td>
<td style="font-weight: bold; text-align:right">22,885</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">84,254,857</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>523</td><td>18,887</td><td>44</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
<td style="font-weight: bold; text-align:right">146,668</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,819</td>
<td style="font-weight: bold; text-align:right;">7,677 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+50</td>
<td style="font-weight: bold; text-align:right">114,931</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,943</td>
<td style="text-align:right;font-weight:bold;">24,060</td>
<td style="font-weight: bold; text-align:right">2,547</td>
<td style="font-weight: bold; text-align:right">1,748</td>
<td style="font-weight: bold; text-align:right">92</td>
<td style="font-weight: bold; text-align:right">896,571</td>
<td style="font-weight: bold; text-align:right">10,687</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/iran-population/">83,892,015</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>572</td><td>10,928</td><td>94</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
<td style="font-weight: bold; text-align:right">141,779</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">4,099 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">59,442</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">78,238</td>
<td style="font-weight: bold; text-align:right">926</td>
<td style="font-weight: bold; text-align:right">4,306</td>
<td style="font-weight: bold; text-align:right">124</td>
<td style="font-weight: bold; text-align:right">928,797</td>
<td style="font-weight: bold; text-align:right">28,207</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">32,928,451</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>232</td><td>8,033</td><td>35</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/canada/">Canada</a></td>
<td style="font-weight: bold; text-align:right">88,512</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">6,877 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">46,840</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">34,795</td>
<td style="font-weight: bold; text-align:right">1,613</td>
<td style="font-weight: bold; text-align:right">2,347</td>
<td style="font-weight: bold; text-align:right">182</td>
<td style="font-weight: bold; text-align:right">1,585,235</td>
<td style="font-weight: bold; text-align:right">42,036</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/canada-population/">37,711,800</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>426</td><td>5,484</td><td>24</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/chile/">Chile</a></td>
<td style="font-weight: bold; text-align:right">86,943</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">890 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,150</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">49,903</td>

In [23]:
tags = ['tr']
rows = tbody.find_all('tr')
l_o_l = [[x.text for x in row.find_all('td')] for row in rows]
l_o_l

[['',
  '\nNorth America\n',
  '1,985,494',
  '+4,307',
  '120,654',
  '+480',
  '624,697',
  '+2,396',
  '1,240,143',
  '19,456',
  '',
  '',
  '',
  '',
  '',
  'North America',
  '\n',
  '',
  ''],
 ['',
  '\nSouth America\n',
  '758,107',
  '+619',
  '36,746',
  '+13',
  '320,826',
  '+49',
  '400,535',
  '11,077',
  '',
  '',
  '',
  '',
  '',
  'South America',
  '\n',
  '',
  ''],
 ['',
  '\nEurope\n',
  '1,982,048',
  '+12,149',
  '172,017',
  '+449',
  '960,087',
  '+11,591',
  '849,944',
  '9,354',
  '',
  '',
  '',
  '',
  '',
  'Europe',
  '\n',
  '',
  ''],
 ['',
  '\nAsia\n',
  '1,069,380',
  '+18,114',
  '29,399',
  '+279',
  '635,449',
  '+13,705',
  '404,532',
  '13,704',
  '',
  '',
  '',
  '',
  '',
  'Asia',
  '\n',
  '',
  ''],
 ['',
  '\nAfrica\n',
  '132,668',
  '+1,081',
  '3,820',
  '+6',
  '55,300',
  '+174',
  '73,548',
  '355',
  '',
  '',
  '',
  '',
  '',
  'Africa',
  '\n',
  '',
  ''],
 ['',
  '\nOceania\n',
  '8,782',
  '+23',
  '125',
  '',
  '8,164',
  '+9',
  '493',
  '4',
  '',
  '',
  '',
  '',
  '',
  'Australia/Oceania',
  '\n',
  '',
  ''],
 ['',
  '\n\n',
  '721',
  '',
  '15',
  '',
  '651',
  '',
  '55',
  '4',
  '',
  '',
  '',
  '',
  '',
  '',
  '\n',
  '',
  ''],
 ['',
  'World',
  '5,937,200',
  '+36,293',
  '362,776',
  '+1,227',
  '2,605,174',
  '+27,924',
  '2,969,250',
  '53,954',
  '762',
  '46.5',
  '',
  '',
  '',
  'All',
  '\n',
  '',
  ''],
 ['1',
  'USA',
  '1,768,868',
  '+407',
  '103,345 ',
  '+15',
  '498,762',
  '+37',
  '1,166,761',
  '17,202',
  '5,347',
  '312',
  '16,333,027',
  '49,370',
  '330,827,597 ',
  'North America',
  '187',
  '3,201',
  '20'],
 ['2',
  'Brazil',
  '438,812',
  '',
  '26,764 ',
  '',
  '193,181',
  '',
  '218,867',
  '8,318',
  '2,066',
  '126',
  '871,839',
  '4,104',
  '212,422,152 ',
  'South America',
  '484',
  '7,937',
  '244'],
 ['3',
  'Russia',
  '387,623',
  '+8,572',
  '4,374 ',
  '+232',
  '159,257',
  '+8,264',
  '223,992',
  '2,300',
  '2,656',
  '30',
  '10,000,061',
  '68,527',
  '145,928,996 ',
  'Europe',
  '376',
  '33,363',
  '15'],
 ['4',
  'Spain',
  '284,986',
  '',
  '27,119 ',
  '',
  '196,958',
  '',
  '60,909',
  '854',
  '6,096',
  '580',
  '3,556,567',
  '76,071',
  '46,753,197 ',
  'Europe',
  '164',
  '1,724',
  '13'],
 ['5',
  'UK',
  '269,127',
  '',
  '37,837 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '1,559',
  '3,966',
  '558',
  '3,918,079',
  '57,743',
  '67,853,964 ',
  'Europe',
  '252',
  '1,793',
  '17'],
 ['6',
  'Italy',
  '231,732',
  '',
  '33,142 ',
  '',
  '150,604',
  '',
  '47,986',
  '489',
  '3,832',
  '548',
  '3,683,144',
  '60,909',
  '60,469,504 ',
  'Europe',
  '261',
  '1,825',
  '16'],
 ['7',
  'France',
  '186,238',
  '',
  '28,662 ',
  '',
  '67,191',
  '',
  '90,385',
  '1,429',
  '2,854',
  '439',
  '1,384,633',
  '21,217',
  '65,260,761 ',
  'Europe',
  '350',
  '2,277',
  '47'],
 ['8',
  'Germany',
  '182,495',
  '+43',
  '8,574 ',
  '+4',
  '164,100',
  '+900',
  '9,821',
  '744',
  '2,179',
  '102',
  '3,952,971',
  '47,194',
  '83,760,156 ',
  'Europe',
  '459',
  '9,769',
  '21'],
 ['9',
  'India',
  '167,451',
  '+2,065',
  '4,797 ',
  '+86',
  '71,410',
  '+490',
  '91,244',
  '8,944',
  '121',
  '3',
  '3,483,838',
  '2,527',
  '1,378,752,175 ',
  'Asia',
  '8,234',
  '287,420',
  '396'],
 ['10',
  'Turkey',
  '160,979',
  '',
  '4,461 ',
  '',
  '124,369',
  '',
  '32,149',
  '683',
  '1,911',
  '53',
  '1,928,209',
  '22,885',
  '84,254,857 ',
  'Asia',
  '523',
  '18,887',
  '44'],
 ['11',
  'Iran',
  '146,668',
  '+2,819',
  '7,677 ',
  '+50',
  '114,931',
  '+1,943',
  '24,060',
  '2,547',
  '1,748',
  '92',
  '896,571',
  '10,687',
  '83,892,015 ',
  'Asia',
  '572',
  '10,928',
  '94'],
 ['12',
  'Peru',
  '141,779',
  '',
  '4,099 ',
  '',
  '59,442',
  '',
  '78,238',
  '926',
  '4,306',
  '124',
  '928,797',
  '28,207',
  '32,928,451 ',
  'South America',
  '232',
  '8,033',
  '35'],
 ['13',
  'Canada',
  '88,512',
  '',
  '6,877 ',
  '',
  '46,840',
  '',
  '34,795',
  '1,613',
  '2,347',
  '182',
  '1,585,235',
  '42,036',
  '37,711,800 ',
  'North America',
  '426',
  '5,484',
  '24'],
 ['14',
  'Chile',
  '86,943',
  '',
  '890 ',
  '',
  '36,150',
  '',
  '49,903',
  '1,289',
  '4,552',
  '47',
  '530,173',
  '27,756',
  '19,101,165 ',
  'South America',
  '220',
  '21,462',
  '36'],
 ['15',
  'Saudi Arabia',
  '81,766',
  '+1,581',
  '458 ',
  '+17',
  '57,013',
  '+2,460',
  '24,295',
  '384',
  '2,352',
  '13',
  '787,465',
  '22,653',
  '34,762,153 ',
  'Asia',
  '425',
  '75,900',
  '44'],
 ['16',
  'Mexico',
  '81,400',
  '+3,377',
  '9,044 ',
  '+447',
  '56,638',
  '+2,255',
  '15,718',
  '378',
  '632',
  '70',
  '244,858',
  '1,901',
  '128,807,241 ',
  'North America',
  '1,582',
  '14,242',
  '526'],
 ['17',
  'Pakistan',
  '64,028',
  '+2,801',
  '1,317 ',
  '+57',
  '22,305',
  '+2,074',
  '40,406',
  '111',
  '290',
  '6',
  '520,017',
  '2,359',
  '220,474,171 ',
  'Asia',
  '3,443',
  '167,406',
  '424'],
 ['18',
  'Belgium',
  '58,061',
  '+212',
  '9,430 ',
  '+42',
  '15,682',
  '+110',
  '32,949',
  '187',
  '5,012',
  '814',
  '836,879',
  '72,237',
  '11,585,114 ',
  'Europe',
  '200',
  '1,229',
  '14'],
 ['19',
  'Qatar',
  '52,907',
  '+1,993',
  '36 ',
  '+3',
  '20,604',
  '+5,205',
  '32,267',
  '216',
  '18,394',
  '13',
  '212,897',
  '74,016',
  '2,876,377 ',
  'Asia',
  '54',
  '79,899',
  '14'],
 ['20',
  'Netherlands',
  '46,126',
  '+176',
  '5,931 ',
  '+28',
  'N/A',
  'N/A',
  'N/A',
  '182',
  '2,692',
  '346',
  '348,256',
  '20,328',
  '17,131,525 ',
  'Europe',
  '371',
  '2,888',
  '49'],
 ['21',
  'Bangladesh',
  '42,844',
  '+2,523',
  '582 ',
  '+23',
  '9,015',
  '+590',
  '33,247',
  '1',
  '260',
  '4',
  '287,067',
  '1,745',
  '164,537,836 ',
  'Asia',
  '3,840',
  '282,711',
  '573'],
 ['22',
  'Belarus',
  '40,764',
  '+906',
  '224 ',
  '+5',
  '17,390',
  '+730',
  '23,150',
  '92',
  '4,314',
  '24',
  '512,418',
  '54,226',
  '9,449,593 ',
  'Europe',
  '232',
  '42,186',
  '18'],
 ['23',
  'Ecuador',
  '38,471',
  '',
  '3,313 ',
  '',
  '18,425',
  '',
  '16,733',
  '220',
  '2,184',
  '188',
  '110,812',
  '6,290',
  '17,617,555 ',
  'South America',
  '458',
  '5,318',
  '159'],
 ['24',
  'Sweden',
  '36,476',
  '+749',
  '4,350 ',
  '+84',
  '4,971',
  '',
  '27,155',
  '289',
  '3,614',
  '431',
  '238,800',
  '23,659',
  '10,093,573 ',
  'Europe',
  '277',
  '2,320',
  '42'],
 ['25',
  'Singapore',
  '33,860',
  '+611',
  '23 ',
  '',
  '18,294',
  '',
  '15,543',
  '7',
  '5,792',
  '4',
  '334,691',
  '57,250',
  '5,846,144 ',
  'Asia',
  '173',
  '254,180',
  '17'],
 ['26',
  'UAE',
  '32,532',
  '',
  '258 ',
  '',
  '16,685',
  '',
  '15,589',
  '1',
  '3,293',
  '26',
  '2,110,493',
  '213,629',
  '9,879,229 ',
  'Asia',
  '304',
  '38,292',
  '5'],
 ['27',
  'Portugal',
  '31,946',
  '+350',
  '1,383 ',
  '+14',
  '18,911',
  '+274',
  '11,652',
  '66',
  '3,132',
  '136',
  '778,698',
  '76,349',
  '10,199,255 ',
  'Europe',
  '319',
  '7,375',
  '13'],
 ['28',
  'Switzerland',
  '30,828',
  '+32',
  '1,919 ',
  '',
  '28,300',
  '',
  '609',
  '32',
  '3,564',
  '222',
  '390,697',
  '45,173',
  '8,648,865 ',
  'Europe',
  '281',
  '4,507',
  '22'],
 ['29',
  'South Africa',
  '27,403',
  '',
  '577 ',
  '',
  '14,370',
  '',
  '12,456',
  '128',
  '463',
  '10',
  '655,723',
  '11,069',
  '59,238,562 ',
  'Africa',
  '2,162',
  '102,666',
  '90'],
 ['30',
  'Colombia',
  '25,366',
  '',
  '822 ',
  '',
  '6,665',
  '',
  '17,879',
  '136',
  '499',
  '16',
  '283,346',
  '5,574',
  '50,832,596 ',
  'South America',
  '2,004',
  '61,840',
  '179'],
 ['31',
  'Indonesia',
  '25,216',
  '+678',
  '1,520 ',
  '+24',
  '6,492',
  '+252',
  '17,204',
  '',
  '92',
  '6',
  '300,545',
  '1,100',
  '273,255,522 ',
  'Asia',
  '10,837',
  '179,773',
  '909'],
 ['32',
  'Ireland',
  '24,841',
  '',
  '1,639 ',
  '',
  '22,089',
  '',
  '1,113',
  '47',
  '5,036',
  '332',
  '325,795',
  '66,049',
  '4,932,656 ',
  'Europe',
  '199',
  '3,010',
  '15'],
 ['33',
  'Kuwait',
  '24,112',
  '',
  '185 ',
  '',
  '8,698',
  '',
  '15,229',
  '197',
  '5,654',
  '43',
  '282,341',
  '66,206',
  '4,264,573 ',
  'Asia',
  '177',
  '23,052',
  '15'],
 ['34',
  'Poland',
  '22,964',
  '+139',
  '1,043 ',
  '+5',
  '10,692',
  '+132',
  '11,229',
  '160',
  '607',
  '28',
  '873,456',
  '23,077',
  '37,850,199 ',
  'Europe',
  '1,648',
  '36,290',
  '43'],
 ['35',
  'Ukraine',
  '22,811',
  '+429',
  '679 ',
  '+10',
  '8,934',
  '+495',
  '13,198',
  '267',
  '521',
  '16',
  '337,318',
  '7,709',
  '43,755,845 ',
  'Europe',
  '1,918',
  '64,442',
  '130'],
 ['36',
  'Egypt',
  '20,793',
  '',
  '845 ',
  '',
  '5,359',
  '',
  '14,589',
  '41',
  '204',
  '8',
  '135,000',
  '1,322',
  '102,146,819 ',
  'Africa',
  '4,913',
  '120,884',
  '757'],
 ['37',
  'Romania',
  '18,982',
  '+191',
  '1,240 ',
  '+5',
  '12,829',
  '+200',
  '4,913',
  '182',
  '986',
  '64',
  '421,451',
  '21,895',
  '19,248,434 ',
  'Europe',
  '1,014',
  '15,523',
  '46'],
 ['38',
  'Israel',
  '16,887',
  '+15',
  '284 ',
  '',
  '14,727',
  '+48',
  '1,876',
  '37',
  '1,836',
  '31',
  '565,311',
  '61,463',
  '9,197,590 ',
  'Asia',
  '545',
  '32,386',
  '16'],
 ['39',
  'Japan',
  '16,683',
  '',
  '867 ',
  '',
  '14,147',
  '',
  '1,669',
  '136',
  '132',
  '7',
  '281,293',
  '2,223',
  '126,509,583 ',
  'Asia',
  '7,583',
  '145,916',
  '450'],
 ['40',
  'Austria',
  '16,655',
  '+27',
  '668 ',
  '',
  '15,347',
  '+61',
  '640',
  '25',
  '1,850',
  '74',
  '434,302',
  '48,246',
  '9,001,768 ',
  'Europe',
  '540',
  '13,476',
  '21'],
 ['41',
  'Dominican Republic',
  '16,068',
  '',
  '485 ',
  '',
  '8,952',
  '',
  '6,631',
  '123',
  '1,483',
  '45',
  '74,612',
  '6,884',
  '10,837,859 ',
  'North America',
  '674',
  '22,346',
  '145'],
 ['42',
  'Philippines',
  '15,588',
  '',
  '921 ',
  '',
  '3,598',
  '',
  '11,069',
  '81',
  '142',
  '8',
  '323,819',
  '2,959',
  '109,443,743 ',
  'Asia',
  '7,021',
  '118,831',
  '338'],
 ['43',
  'Argentina',
  '14,702',
  '',
  '508 ',
  '',
  '4,617',
  '',
  '9,577',
  '171',
  '326',
  '11',
  '145,081',
  '3,213',
  '45,157,642 ',
  'South America',
  '3,072',
  '88,893',
  '311'],
 ['44',
  'Afghanistan',
  '13,659',
  '+623',
  '246 ',
  '+11',
  '1,259',
  '+50',
  '12,154',
  '19',
  '352',
  '6',
  '35,923',
  '925',
  '38,841,361 ',
  'Asia',
  '2,844',
  '157,892',
  '1,081'],
 ['45',
  'Panama',
  '12,131',
  '',
  '320 ',
  '',
  '7,379',
  '',
  '4,432',
  '72',
  '2,816',
  '74',
  '63,202',
  '14,670',
  '4,308,282 ',
  'North America',
  '355',
  '13,463',
  '68'],
 ['46',
  'Denmark',
  '11,593',
  '+81',
  '568 ',
  '',
  '10,240',
  '+60',
  '785',
  '18',
  '2,002',
  '98',
  '606,574',
  '104,755',
  '5,790,388 ',
  'Europe',
  '499',
  '10,194',
  '10'],
 ['47',
  'S. Korea',
  '11,402',
  '+58',
  '269 ',
  '',
  '10,363',
  '+23',
  '770',
  '15',
  '222',
  '5',
  '885,120',
  '17,265',
  '51,265,321 ',
  'Asia',
  '4,496',
  '190,577',
  '58'],
 ['48',
  'Serbia',
  '11,354',
  '+54',
  '242 ',
  '+1',
  '6,524',
  '+86',
  '4,588',
  '8',
  '1,299',
  '28',
  '239,234',
  '27,371',
  '8,740,364 ',
  'Europe',
  '770',
  '36,117',
  '37'],
 ['49',
  'Bahrain',
  '10,352',
  '+300',
  '15 ',
  '',
  '5,491',
  '+72',
  '4,846',
  '9',
  '6,106',
  '9',
  '302,640',
  '178,518',
  '1,695,292 ',
  'Asia',
  '164',
  '113,019',
  '6'],
 ['50',
  'Kazakhstan',
  '9,932',
  '+356',
  '37 ',
  '',
  '5,011',
  '+111',
  '4,884',
  '62',
  '530',
  '2',
  '761,727',
  '40,613',
  '18,755,722 ',
  'Asia',
  '1,888',
  '506,911',
  '25'],
 ['51',
  'Oman',
  '9,820',
  '+811',
  '40 ',
  '',
  '2,396',
  '+219',
  '7,384',
  '31',
  '1,928',
  '8',
  '72,000',
  '14,136',
  '5,093,528 ',
  'Asia',
  '519',
  '127,338',
  '71'],
 ['52',
  'Czechia',
  '9,143',
  '+3',
  '319 ',
  '',
  '6,464',
  '+4',
  '2,360',
  '19',
  '854',
  '30',
  '430,564',
  '40,212',
  '10,707,231 ',
  'Europe',
  '1,171',
  '33,565',
  '25'],
 ['53',
  'Algeria',
  '8,997',
  '',
  '630 ',
  '',
  '5,277',
  '',
  '3,090',
  '32',
  '206',
  '14',
  '',
  '',
  '43,774,437 ',
  'Africa',
  '4,865',
  '69,483',
  ''],
 ['54',
  'Nigeria',
  '8,915',
  '',
  '259 ',
  '',
  '2,592',
  '',
  '6,064',
  '7',
  '43',
  '1',
  '58,726',
  '286',
  '205,626,178 ',
  'Africa',
  '23,065',
  '793,923',
  '3,501'],
 ['55',
  'Armenia',
  '8,676',
  '+460',
  '120 ',
  '+7',
  '3,297',
  '+10',
  '5,259',
  '10',
  '2,928',
  '41',
  '56,042',
  '18,916',
  '2,962,755 ',
  'Asia',
  '341',
  '24,690',
  '53'],
 ['56',
  'Norway',
  '8,411',
  '',
  '236 ',
  '',
  '7,727',
  '',
  '448',
  '8',
  '1,553',
  '44',
  '245,352',
  '45,290',
  '5,417,374 ',
  'Europe',
  '644',
  '22,955',
  '22'],
 ['57',
  'Bolivia',
  '8,387',
  '+619',
  '293 ',
  '+13',
  '738',
  '+49',
  '7,356',
  '3',
  '719',
  '25',
  '22,294',
  '1,912',
  '11,657,999 ',
  'South America',
  '1,390',
  '39,788',
  '523'],
 ['58',
  'Malaysia',
  '7,732',
  '+103',
  '115 ',
  '',
  '6,235',
  '+66',
  '1,382',
  '8',
  '239',
  '4',
  '519,944',
  '16,084',
  '32,327,063 ',
  'Asia',
  '4,181',
  '281,105',
  '62'],
 ['59',
  'Moldova',
  '7,725',
  '',
  '282 ',
  '',
  '4,123',
  '',
  '3,320',
  '256',
  '1,915',
  '70',
  '40,565',
  '10,054',
  '4,034,769 ',
  'Europe',
  '522',
  '14,308',
  '99'],
 ['60',
  'Morocco',
  '7,697',
  '+54',
  '202 ',
  '',
  '5,223',
  '+28',
  '2,272',
  '1',
  '209',
  '5',
  '185,866',
  '5,041',
  '36,869,708 ',
  'Africa',
  '4,790',
  '182,523',
  '198'],
 ['61',
  'Ghana',
  '7,616',
  '+313',
  '34 ',
  '',
  '2,421',
  '+9',
  '5,161',
  '17',
  '246',
  '1',
  '208,328',
  '6,718',
  '31,009,181 ',
  'Africa',
  '4,072',
  '912,035',
  '149'],
 ['62',
  'Australia',
  '7,173',
  '+23',
  '103 ',
  '',
  '6,582',
  '+2',
  '488',
  '4',
  '282',
  '4',
  '1,397,622',
  '54,868',
  '25,472,297 ',
  'Australia/Oceania',
  '3,551',
  '247,304',
  '18'],
 ['63',
  'Finland',
  '6,776',
  '+33',
  '314  ',
  '+1',
  '5,500',
  '',
  '962',
  '10',
  '1,223',
  '57',
  '179,400',
  '32,383',
  '5,539,963 ',
  'Europe',
  '818',
  '17,643',
  '31'],
 ['64',
  'Iraq',
  '5,457',
  '',
  '179 ',
  '',
  '2,971',
  '',
  '2,307',
  '41',
  '136',
  '4',
  '211,485',
  '5,270',
  '40,132,981 ',
  'Asia',
  '7,354',
  '224,207',
  '190'],
 ['65',
  'Cameroon',
  '5,436',
  '',
  '175 ',
  '',
  '1,996',
  '',
  '3,265',
  '28',
  '205',
  '7',
  '',
  '',
  '26,479,422 ',
  'Africa',
  '4,871',
  '151,311',
  ''],
 ['66',
  'Azerbaijan',
  '4,759',
  '',
  '56 ',
  '',
  '3,022',
  '',
  '1,681',
  '42',
  '470',
  '6',
  '284,669',
  '28,099',
  '10,130,782 ',
  'Asia',
  '2,129',
  '180,907',
  '36'],
 ['67',
  'Honduras',
  '4,752',
  '+112',
  '196 ',
  '+2',
  '519',
  '+13',
  '4,037',
  '13',
  '481',
  '20',
  '14,790',
  '1,496',
  '9,889,552 ',
  'North America',
  '2,081',
  '50,457',
  '669'],
 ['68',
  'Guatemala',
  '4,348',
  '+203',
  '80 ',
  '+12',
  '565',
  '+72',
  '3,703',
  '5',
  '243',
  '4',
  '31,427',
  '1,757',
  '17,883,425 ',
  'North America',
  '4,113',
  '223,543',
  '569'],
 ['69',
  'Sudan',
  '4,346',
  '',
  '195 ',
  '',
  '749',
  '',
  '3,402',
  '',
  '99',
  '4',
  '401',
  '9',
  '43,747,206 ',
  'Africa',
  '10,066',
  '224,345',
  '109,095'],
 ['70',
  'Luxembourg',
  '4,008',
  '',
  '110 ',
  '',
  '3,803',
  '',
  '95',
  '4',
  '6,413',
  '176',
  '71,098',
  '113,756',
  '625,003 ',
  'Europe',
  '156',
  '5,682',
  '9'],
 ['71',
  'Hungary',
  '3,841',
  '+25',
  '517 ',
  '+8',
  '2,024',
  '+28',
  '1,300',
  '24',
  '398',
  '54',
  '180,152',
  '18,645',
  '9,662,456 ',
  'Europe',
  '2,516',
  '18,689',
  '54'],
 ['72',
  'Tajikistan',
  '3,563',
  '',
  '47 ',
  '',
  '1,674',
  '',
  '1,842',
  '',
  '374',
  '5',
  '',
  '',
  '9,516,398 ',
  'Asia',
  '2,671',
  '202,477',
  ''],
 ['73',
  'Guinea',
  '3,553',
  '',
  '22 ',
  '',
  '1,950',
  '',
  '1,581',
  '24',
  '271',
  '2',
  '14,407',
  '1,100',
  '13,096,527 ',
  'Africa',
  '3,686',
  '595,297',
  '909'],
 ['74',
  'Uzbekistan',
  '3,468',
  '+24',
  '14 ',
  '',
  '2,723',
  '+29',
  '731',
  '7',
  '104',
  '0.4',
  '460,000',
  '13,763',
  '33,423,219 ',
  'Asia',
  '9,638',
  '2,387,373',
  '73'],
 ['75',
  'Senegal',
  '3,429',
  '+81',
  '41 ',
  '+2',
  '1,738',
  '+52',
  '1,650',
  '18',
  '205',
  '2',
  '39,499',
  '2,365',
  '16,699,197 ',
  'Africa',
  '4,870',
  '407,297',
  '423'],
 ['76',
  'Thailand',
  '3,076',
  '+11',
  '57 ',
  '',
  '2,945',
  '',
  '74',
  '59',
  '44',
  '0.8',
  '375,453',
  '5,380',
  '69,784,490 ',
  'Asia',
  '22,687',
  '1,224,289',
  '186'],
 ['77',
  'Djibouti',
  '2,914',
  '',
  '20 ',
  '',
  '1,241',
  '',
  '1,653',
  '',
  '2,953',
  '20',
  '25,257',
  '25,599',
  '986,638 ',
  'Africa',
  '339',
  '49,332',
  '39'],
 ['78',
  'Greece',
  '2,906',
  '',
  '175 ',
  '',
  '1,374',
  '',
  '1,357',
  '16',
  '279',
  '17',
  '170,467',
  '16,348',
  '10,427,362 ',
  'Europe',
  '3,588',
  '59,585',
  '61'],
 ['79',
  'DRC',
  '2,833',
  '+173',
  '69 ',
  '',
  '400',
  '+19',
  '2,364',
  '',
  '32',
  '0.8',
  '',
  '',
  '89,279,074 ',
  'Africa',
  '31,514',
  '1,293,900',
  ''],
 ['80',
  'Ivory Coast',
  '2,641',
  '',
  '32 ',
  '',
  '1,326',
  '',
  '1,283',
  '',
  '100',
  '1',
  '26,021',
  '989',
  '26,312,643 ',
  'Africa',
  '9,963',
  '822,270',
  '1,011'],
 ['81',
  'Bosnia and Herzegovina',
  '2,485',
  '+23',
  '153 ',
  '',
  '1,803',
  '+22',
  '529',
  '4',
  '757',
  '47',
  '63,596',
  '19,374',
  '3,282,532 ',
  'Europe',
  '1,321',
  '21,454',
  '52'],
 ['82',
  'Bulgaria',
  '2,485',
  '+8',
  '136 ',
  '+2',
  '1,016',
  '+51',
  '1,333',
  '22',
  '357',
  '20',
  '79,389',
  '11,418',
  '6,952,801 ',
  'Europe',
  '2,798',
  '51,124',
  '88'],
 ['83',
  'Gabon',
  '2,431',
  '',
  '14 ',
  '',
  '668',
  '',
  '1,749',
  '15',
  '1,095',
  '6',
  '12,669',
  '5,705',
  '2,220,492 ',
  'Africa',
  '913',
  '158,607',
  '175'],
 ['84',
  'El Salvador',
  '2,278',
  '+84',
  '42 ',
  '+3',
  '1,015',
  '+13',
  '1,221',
  '30',
  '351',
  '6',
  '84,650',
  '13,057',
  '6,483,267 ',
  'North America',
  '2,846',
  '154,364',
  '77'],
 ['85',
  'Croatia',
  '2,245',
  '',
  '103 ',
  '+1',
  '2,059',
  '+8',
  '83',
  '4',
  '547',
  '25',
  '65,509',
  '15,949',
  '4,107,393 ',
  'Europe',
  '1,830',
  '39,878',
  '63'],
 ['86',
  'North Macedonia',
  '2,129',
  '+52',
  '126 ',
  '+5',
  '1,516',
  '+30',
  '487',
  '21',
  '1,022',
  '60',
  '27,684',
  '13,288',
  '2,083,381 ',
  'Europe',
  '979',
  '16,535',
  '75'],
 ['87',
  'Cuba',
  '1,983',
  '',
  '82 ',
  '',
  '1,734',
  '',
  '167',
  '2',
  '175',
  '7',
  '99,745',
  '8,806',
  '11,327,216 ',
  'North America',
  '5,712',
  '138,137',
  '114'],
 ['88',
  'Estonia',
  '1,859',
  '+8',
  '67 ',
  '+1',
  '1,610',
  '+36',
  '182',
  '',
  '1,401',
  '51',
  '81,719',
  '61,607',
  '1,326,457 ',
  'Europe',
  '714',
  '19,798',
  '16'],
 ['89',
  'Somalia',
  '1,828',
  '',
  '72 ',
  '',
  '310',
  '',
  '1,446',
  '2',
  '115',
  '5',
  '',
  '',
  '15,847,882 ',
  'Africa',
  '8,670',
  '220,109',
  ''],
 ['90',
  'Iceland',
  '1,805',
  '',
  '10 ',
  '',
  '1,794',
  '+2',
  '1',
  '',
  '5,293',
  '29',
  '60,491',
  '177,371',
  '341,043 ',
  'Europe',
  '189',
  '34,104',
  '6'],
 ['91',
  'Mayotte',
  '1,670',
  '',
  '21 ',
  '',
  '1,315',
  '',
  '334',
  '10',
  '6,136',
  '77',
  '5,200',
  '19,107',
  '272,156 ',
  'Africa',
  '163',
  '12,960',
  '52'],
 ['92',
  'Lithuania',
  '1,662',
  '+6',
  '68 ',
  '',
  '1,216',
  '+23',
  '378',
  '17',
  '610',
  '25',
  '294,091',
  '107,910',
  '2,725,331 ',
  'Europe',
  '1,640',
  '40,078',
  '9'],
 ['93',
  'Kyrgyzstan',
  '1,662',
  '+68',
  '16 ',
  '',
  '1,088',
  '+22',
  '558',
  '4',
  '255',
  '2',
  '109,521',
  '16,813',
  '6,513,873 ',
  'Asia',
  '3,919',
  '407,117',
  '59'],
 ['94',
  'Kenya',
  '1,618',

In [26]:
import pandas as pd
tbodyDF = pd.DataFrame(l_o_l)

In [31]:
tbodyDF.head(60)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,,\nNorth America\n,"1,985,494","+4,307","120,654",+480,"624,697","+2,396","1,240,143","19,456",,,,,,North America,\n,,
1,,\nSouth America\n,"758,107",+619,"36,746",+13,"320,826",+49,"400,535","11,077",,,,,,South America,\n,,
2,,\nEurope\n,"1,982,048","+12,149","172,017",+449,"960,087","+11,591","849,944","9,354",,,,,,Europe,\n,,
3,,\nAsia\n,"1,069,380","+18,114","29,399",+279,"635,449","+13,705","404,532","13,704",,,,,,Asia,\n,,
4,,\nAfrica\n,"132,668","+1,081","3,820",+6,"55,300",+174,"73,548",355,,,,,,Africa,\n,,
5,,\nOceania\n,"8,782",+23,125,,"8,164",+9,493,4,,,,,,Australia/Oceania,\n,,
6,,\n\n,721,,15,,651,,55,4,,,,,,,\n,,
7,,World,"5,937,200","+36,293","362,776","+1,227","2,605,174","+27,924","2,969,250","53,954",762,46.5,,,,All,\n,,
8,1,USA,"1,768,868",+407,"103,345",+15,"498,762",+37,"1,166,761","17,202","5,347",312,"16,333,027","49,370","330,827,597",North America,187,"3,201",20
9,2,Brazil,"438,812",,"26,764",,"193,181",,"218,867","8,318","2,066",126,"871,839","4,104","212,422,152",South America,484,"7,937",244
10,3,Russia,"387,623","+8,572","4,374",+232,"159,257","+8,264","223,992","2,300","2,656",30,"10,000,061","68,527","145,928,996",Europe,376,"33,363",15
11,4,Spain,"284,986",,"27,119",,"196,958",,"60,909",854,"6,096",580,"3,556,567","76,071","46,753,197",Europe,164,"1,724",13
12,5,UK,"269,127",,"37,837",,N/A,N/A,N/A,"1,559","3,966",558,"3,918,079","57,743","67,853,964",Europe,252,"1,793",17
13,6,Italy,"231,732",,"33,142",,"150,604",,"47,986",489,"3,832",548,"3,683,144","60,909","60,469,504",Europe,261,"1,825",16
14,7,France,"186,238",,"28,662",,"67,191",,"90,385","1,429","2,854",439,"1,384,633","21,217","65,260,761",Europe,350,"2,277",47
15,8,Germany,"182,495",+43,"8,574",+4,"164,100",+900,"9,821",744,"2,179",102,"3,952,971","47,194","83,760,156",Europe,459,"9,769",21
16,9,India,"167,451","+2,065","4,797",+86,"71,410",+490,"91,244","8,944",121,3,"3,483,838","2,527","1,378,752,175",Asia,"8,234","287,420",396
17,10,Turkey,"160,979",,"4,461",,"124,369",,"32,149",683,"1,911",53,"1,928,209","22,885","84,254,857",Asia,523,"18,887",44
18,11,Iran,"146,668","+2,819","7,677",+50,"114,931","+1,943","24,060","2,547","1,748",92,"896,571","10,687","83,892,015",Asia,572,"10,928",94
19,12,Peru,"141,779",,"4,099",,"59,442",,"78,238",926,"4,306",124,"928,797","28,207","32,928,451",South America,232,"8,033",35
20,13,Canada,"88,512",,"6,877",,"46,840",,"34,795","1,613","2,347",182,"1,585,235","42,036","37,711,800",North America,426,"5,484",24
21,14,Chile,"86,943",,890,,"36,150",,"49,903","1,289","4,552",47,"530,173","27,756","19,101,165",South America,220,"21,462",36
22,15,Saudi Arabia,"81,766","+1,581",458,+17,"57,013","+2,460","24,295",384,"2,352",13,"787,465","22,653","34,762,153",Asia,425,"75,900",44
23,16,Mexico,"81,400","+3,377","9,044",+447,"56,638","+2,255","15,718",378,632,70,"244,858","1,901","128,807,241",North America,"1,582","14,242",526
24,17,Pakistan,"64,028","+2,801","1,317",+57,"22,305","+2,074","40,406",111,290,6,"520,017","2,359","220,474,171",Asia,"3,443","167,406",424
25,18,Belgium,"58,061",+212,"9,430",+42,"15,682",+110,"32,949",187,"5,012",814,"836,879","72,237","11,585,114",Europe,200,"1,229",14
26,19,Qatar,"52,907","+1,993",36,+3,"20,604","+5,205","32,267",216,"18,394",13,"212,897","74,016","2,876,377",Asia,54,"79,899",14
27,20,Netherlands,"46,126",+176,"5,931",+28,N/A,N/A,N/A,182,"2,692",346,"348,256","20,328","17,131,525",Europe,371,"2,888",49
28,21,Bangladesh,"42,844","+2,523",582,+23,"9,015",+590,"33,247",1,260,4,"287,067","1,745","164,537,836",Asia,"3,840","282,711",573
29,22,Belarus,"40,764",+906,224,+5,"17,390",+730,"23,150",92,"4,314",24,"512,418","54,226","9,449,593",Europe,232,"42,186",18
30,23,Ecuador,"38,471",,"3,313",,"18,425",,"16,733",220,"2,184",188,"110,812","6,290","17,617,555",South America,458,"5,318",159
31,24,Sweden,"36,476",+749,"4,350",+84,"4,971",,"27,155",289,"3,614",431,"238,800","23,659","10,093,573",Europe,277,"2,320",42
32,25,Singapore,"33,860",+611,23,,"18,294",,"15,543",7,"5,792",4,"334,691","57,250","5,846,144",Asia,173,"254,180",17
33,26,UAE,"32,532",,258,,"16,685",,"15,589",1,"3,293",26,"2,110,493","213,629","9,879,229",Asia,304,"38,292",5
34,27,Portugal,"31,946",+350,"1,383",+14,"18,911",+274,"11,652",66,"3,132",136,"778,698","76,349","10,199,255",Europe,319,"7,375",13
35,28,Switzerland,"30,828",+32,"1,919",,"28,300",,609,32,"3,564",222,"390,697","45,173","8,648,865",Europe,281,"4,507",22
36,29,South Africa,"27,403",,577,,"14,370",,"12,456",128,463,10,"655,723","11,069","59,238,562",Africa,"2,162","102,666",90
37,30,Colombia,"25,366",,822,,"6,665",,"17,879",136,499,16,"283,346","5,574","50,832,596",South America,"2,004","61,840",179
38,31,Indonesia,"25,216",+678,"1,520",+24,"6,492",+252,"17,204",,92,6,"300,545","1,100","273,255,522",Asia,"10,837","179,773",909
39,32,Ireland,"24,841",,"1,639",,"22,089",,"1,113",47,"5,036",332,"325,795","66,049","4,932,656",Europe,199,"3,010",15
40,33,Kuwait,"24,112",,185,,"8,698",,"15,229",197,"5,654",43,"282,341","66,206","4,264,573",Asia,177,"23,052",15
41,34,Poland,"22,964",+139,"1,043",+5,"10,692",+132,"11,229",160,607,28,"873,456","23,077","37,850,199",Europe,"1,648","36,290",43
42,35,Ukraine,"22,811",+429,679,+10,"8,934",+495,"13,198",267,521,16,"337,318","7,709","43,755,845",Europe,"1,918","64,442",130
43,36,Egypt,"20,793",,845,,"5,359",,"14,589",41,204,8,"135,000","1,322","102,146,819",Africa,"4,913","120,884",757
44,37,Romania,"18,982",+191,"1,240",+5,"12,829",+200,"4,913",182,986,64,"421,451","21,895","19,248,434",Europe,"1,014","15,523",46
45,38,Israel,"16,887",+15,284,,"14,727",+48,"1,876",37,"1,836",31,"565,311","61,463","9,197,590",Asia,545,"32,386",16
46,39,Japan,"16,683",,867,,"14,147",,"1,669",136,132,7,"281,293","2,223","126,509,583",Asia,"7,583","145,916",450
47,40,Austria,"16,655",+27,668,,"15,347",+61,640,25,"1,850",74,"434,302","48,246","9,001,768",Europe,540,"13,476",21
48,41,Dominican Republic,"16,068",,485,,"8,952",,"6,631",123,"1,483",45,"74,612","6,884","10,837,859",North America,674,"22,346",145
49,42,Philippines,"15,588",,921,,"3,598",,"11,069",81,142,8,"323,819","2,959","109,443,743",Asia,"7,021","118,831",338
50,43,Argentina,"14,702",,508,,"4,617",,"9,577",171,326,11,"145,081","3,213","45,157,642",South America,"3,072","88,893",311
51,44,Afghanistan,"13,659",+623,246,+11,"1,259",+50,"12,154",19,352,6,"35,923",925,"38,841,361",Asia,"2,844","157,892","1,081"
52,45,Panama,"12,131",,320,,"7,379",,"4,432",72,"2,816",74,"63,202","14,670","4,308,282",North America,355,"13,463",68
53,46,Denmark,"11,593",+81,568,,"10,240",+60,785,18,"2,002",98,"606,574","104,755","5,790,388",Europe,499,"10,194",10
54,47,S. Korea,"11,402",+58,269,,"10,363",+23,770,15,222,5,"885,120","17,265","51,265,321",Asia,"4,496","190,577",58
55,48,Serbia,"11,354",+54,242,+1,"6,524",+86,"4,588",8,"1,299",28,"239,234","27,371","8,740,364",Europe,770,"36,117",37
56,49,Bahrain,"10,352",+300,15,,"5,491",+72,"4,846",9,"6,106",9,"302,640","178,518","1,695,292",Asia,164,"113,019",6
57,50,Kazakhstan,"9,932",+356,37,,"5,011",+111,"4,884",62,530,2,"761,727","40,613","18,755,722",Asia,"1,888","506,911",25
58,51,Oman,"9,820",+811,40,,"2,396",+219,"7,384",31,"1,928",8,"72,000","14,136","5,093,528",Asia,519,"127,338",71
59,52,Czechia,"9,143",+3,319,,"6,464",+4,"2,360",19,854,30,"430,564","40,212","10,707,231",Europe,"1,171","33,565",25

In [24]:
rows = table.find_all('tr')
# rows = [row.text.strip().split('\n') for row in rows]
# rows
rows = [row.text.strip().replace('\xa0', '').split('\n') for row in rows]
rows
rows = [[x for x in row if x != ''] for row in rows]
rows

[['#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'TotCases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl'],
 ['North America',
  '1,985,494',
  '+4,307',
  '120,654',
  '+480',
  '624,697',
  '+2,396',
  '1,240,143',
  '19,456',
  'North America'],
 ['South America',
  '758,107',
  '+619',
  '36,746',
  '+13',
  '320,826',
  '+49',
  '400,535',
  '11,077',
  'South America'],
 ['Europe',
  '1,982,048',
  '+12,149',
  '172,017',
  '+449',
  '960,087',
  '+11,591',
  '849,944',
  '9,354',
  'Europe'],
 ['Asia',
  '1,069,380',
  '+18,114',
  '29,399',
  '+279',
  '635,449',
  '+13,705',
  '404,532',
  '13,704',
  'Asia'],
 ['Africa',
  '132,668',
  '+1,081',
  '3,820',
  '+6',
  '55,300',
  '+174',
  '73,548',
  '355',
  'Africa'],
 ['Oceania',
  '8,782',
  '+23',
  '125',
  '8,164',
  '+9',
  '493',
  '4',
  'Australia/Oceania'],
 ['721', '15', '651', '55', '4'],
 ['World',
  '5,937,200',
  '+36,293',
  '362,776',
  '+1,227',
  '2,605,174',
  '+27,924',
  '2,969,250',
  '53,954',
  '762',
  '46.5',
  'All'],
 ['1',
  'USA',
  '1,768,868',
  '+407',
  '103,345 ',
  '+15',
  '498,762',
  '+37',
  '1,166,761',
  '17,202',
  '5,347',
  '312',
  '16,333,027',
  '49,370',
  '330,827,597 ',
  'North America',
  '1873,20120'],
 ['2',
  'Brazil',
  '438,812',
  '26,764 ',
  '193,181',
  '218,867',
  '8,318',
  '2,066',
  '126',
  '871,839',
  '4,104',
  '212,422,152 ',
  'South America',
  '4847,937244'],
 ['3',
  'Russia',
  '387,623',
  '+8,572',
  '4,374 ',
  '+232',
  '159,257',
  '+8,264',
  '223,992',
  '2,300',
  '2,656',
  '30',
  '10,000,061',
  '68,527',
  '145,928,996 ',
  'Europe',
  '37633,36315'],
 ['4',
  'Spain',
  '284,986',
  '27,119 ',
  '196,958',
  '60,909',
  '854',
  '6,096',
  '580',
  '3,556,567',
  '76,071',
  '46,753,197 ',
  'Europe',
  '1641,72413'],
 ['5',
  'UK',
  '269,127',
  '37,837 ',
  'N/A',
  'N/A',
  'N/A',
  '1,559',
  '3,966',
  '558',
  '3,918,079',
  '57,743',
  '67,853,964 ',
  'Europe',
  '2521,79317'],
 ['6',
  'Italy',
  '231,732',
  '33,142 ',
  '150,604',
  '47,986',
  '489',
  '3,832',
  '548',
  '3,683,144',
  '60,909',
  '60,469,504 ',
  'Europe',
  '2611,82516'],
 ['7',
  'France',
  '186,238',
  '28,662 ',
  '67,191',
  '90,385',
  '1,429',
  '2,854',
  '439',
  '1,384,633',
  '21,217',
  '65,260,761 ',
  'Europe',
  '3502,27747'],
 ['8',
  'Germany',
  '182,495',
  '+43',
  '8,574 ',
  '+4',
  '164,100',
  '+900',
  '9,821',
  '744',
  '2,179',
  '102',
  '3,952,971',
  '47,194',
  '83,760,156 ',
  'Europe',
  '4599,76921'],
 ['9',
  'India',
  '167,451',
  '+2,065',
  '4,797 ',
  '+86',
  '71,410',
  '+490',
  '91,244',
  '8,944',
  '121',
  '3',
  '3,483,838',
  '2,527',
  '1,378,752,175 ',
  'Asia',
  '8,234287,420396'],
 ['10',
  'Turkey',
  '160,979',
  '4,461 ',
  '124,369',
  '32,149',
  '683',
  '1,911',
  '53',
  '1,928,209',
  '22,885',
  '84,254,857 ',
  'Asia',
  '52318,88744'],
 ['11',
  'Iran',
  '146,668',
  '+2,819',
  '7,677 ',
  '+50',
  '114,931',
  '+1,943',
  '24,060',
  '2,547',
  '1,748',
  '92',
  '896,571',
  '10,687',
  '83,892,015 ',
  'Asia',
  '57210,92894'],
 ['12',
  'Peru',
  '141,779',
  '4,099 ',
  '59,442',
  '78,238',
  '926',
  '4,306',
  '124',
  '928,797',
  '28,207',
  '32,928,451 ',
  'South America',
  '2328,03335'],
 ['13',
  'Canada',
  '88,512',
  '6,877 ',
  '46,840',
  '34,795',
  '1,613',
  '2,347',
  '182',
  '1,585,235',
  '42,036',
  '37,711,800 ',
  'North America',
  '4265,48424'],
 ['14',
  'Chile',
  '86,943',
  '890 ',
  '36,150',
  '49,903',
  '1,289',
  '4,552',
  '47',
  '530,173',
  '27,756',
  '19,101,165 ',
  'South America',
  '22021,46236'],
 ['15',
  'Saudi Arabia',
  '81,766',
  '+1,581',
  '458 ',
  '+17',
  '57,013',
  '+2,460',
  '24,295',
  '384',
  '2,352',
  '13',
  '787,465',
  '22,653',
  '34,762,153 ',
  'Asia',
  '42575,90044'],
 ['16',
  'Mexico',
  '81,400',
  '+3,377',
  '9,044 ',
  '+447',
  '56,638',
  '+2,255',
  '15,718',
  '378',
  '632',
  '70',
  '244,858',
  '1,901',
  '128,807,241 ',
  'North America',
  '1,58214,242526'],
 ['17',
  'Pakistan',
  '64,028',
  '+2,801',
  '1,317 ',
  '+57',
  '22,305',
  '+2,074',
  '40,406',
  '111',
  '290',
  '6',
  '520,017',
  '2,359',
  '220,474,171 ',
  'Asia',
  '3,443167,406424'],
 ['18',
  'Belgium',
  '58,061',
  '+212',
  '9,430 ',
  '+42',
  '15,682',
  '+110',
  '32,949',
  '187',
  '5,012',
  '814',
  '836,879',
  '72,237',
  '11,585,114 ',
  'Europe',
  '2001,22914'],
 ['19',
  'Qatar',
  '52,907',
  '+1,993',
  '36 ',
  '+3',
  '20,604',
  '+5,205',
  '32,267',
  '216',
  '18,394',
  '13',
  '212,897',
  '74,016',
  '2,876,377 ',
  'Asia',
  '5479,89914'],
 ['20',
  'Netherlands',
  '46,126',
  '+176',
  '5,931 ',
  '+28',
  'N/A',
  'N/A',
  'N/A',
  '182',
  '2,692',
  '346',
  '348,256',
  '20,328',
  '17,131,525 ',
  'Europe',
  '3712,88849'],
 ['21',
  'Bangladesh',
  '42,844',
  '+2,523',
  '582 ',
  '+23',
  '9,015',
  '+590',
  '33,247',
  '1',
  '260',
  '4',
  '287,067',
  '1,745',
  '164,537,836 ',
  'Asia',
  '3,840282,711573'],
 ['22',
  'Belarus',
  '40,764',
  '+906',
  '224 ',
  '+5',
  '17,390',
  '+730',
  '23,150',
  '92',
  '4,314',
  '24',
  '512,418',
  '54,226',
  '9,449,593 ',
  'Europe',
  '23242,18618'],
 ['23',
  'Ecuador',
  '38,471',
  '3,313 ',
  '18,425',
  '16,733',
  '220',
  '2,184',
  '188',
  '110,812',
  '6,290',
  '17,617,555 ',
  'South America',
  '4585,318159'],
 ['24',
  'Sweden',
  '36,476',
  '+749',
  '4,350 ',
  '+84',
  '4,971',
  '27,155',
  '289',
  '3,614',
  '431',
  '238,800',
  '23,659',
  '10,093,573 ',
  'Europe',
  '2772,32042'],
 ['25',
  'Singapore',
  '33,860',
  '+611',
  '23 ',
  '18,294',
  '15,543',
  '7',
  '5,792',
  '4',
  '334,691',
  '57,250',
  '5,846,144 ',
  'Asia',
  '173254,18017'],
 ['26',
  'UAE',
  '32,532',
  '258 ',
  '16,685',
  '15,589',
  '1',
  '3,293',
  '26',
  '2,110,493',
  '213,629',
  '9,879,229 ',
  'Asia',
  '30438,2925'],
 ['27',
  'Portugal',
  '31,946',
  '+350',
  '1,383 ',
  '+14',
  '18,911',
  '+274',
  '11,652',
  '66',
  '3,132',
  '136',
  '778,698',
  '76,349',
  '10,199,255 ',
  'Europe',
  '3197,37513'],
 ['28',
  'Switzerland',
  '30,828',
  '+32',
  '1,919 ',
  '28,300',
  '609',
  '32',
  '3,564',
  '222',
  '390,697',
  '45,173',
  '8,648,865 ',
  'Europe',
  '2814,50722'],
 ['29',
  'South Africa',
  '27,403',
  '577 ',
  '14,370',
  '12,456',
  '128',
  '463',
  '10',
  '655,723',
  '11,069',
  '59,238,562 ',
  'Africa',
  '2,162102,66690'],
 ['30',
  'Colombia',
  '25,366',
  '822 ',
  '6,665',
  '17,879',
  '136',
  '499',
  '16',
  '283,346',
  '5,574',
  '50,832,596 ',
  'South America',
  '2,00461,840179'],
 ['31',
  'Indonesia',
  '25,216',
  '+678',
  '1,520 ',
  '+24',
  '6,492',
  '+252',
  '17,204',
  '92',
  '6',
  '300,545',
  '1,100',
  '273,255,522 ',
  'Asia',
  '10,837179,773909'],
 ['32',
  'Ireland',
  '24,841',
  '1,639 ',
  '22,089',
  '1,113',
  '47',
  '5,036',
  '332',
  '325,795',
  '66,049',
  '4,932,656 ',
  'Europe',
  '1993,01015'],
 ['33',
  'Kuwait',
  '24,112',
  '185 ',
  '8,698',
  '15,229',
  '197',
  '5,654',
  '43',
  '282,341',
  '66,206',
  '4,264,573 ',
  'Asia',
  '17723,05215'],
 ['34',
  'Poland',
  '22,964',
  '+139',
  '1,043 ',
  '+5',
  '10,692',
  '+132',
  '11,229',
  '160',
  '607',
  '28',
  '873,456',
  '23,077',
  '37,850,199 ',
  'Europe',
  '1,64836,29043'],
 ['35',
  'Ukraine',
  '22,811',
  '+429',
  '679 ',
  '+10',
  '8,934',
  '+495',
  '13,198',
  '267',
  '521',
  '16',
  '337,318',
  '7,709',
  '43,755,845 ',
  'Europe',
  '1,91864,442130'],
 ['36',
  'Egypt',
  '20,793',
  '845 ',
  '5,359',
  '14,589',
  '41',
  '204',
  '8',
  '135,000',
  '1,322',
  '102,146,819 ',
  'Africa',
  '4,913120,884757'],
 ['37',
  'Romania',
  '18,982',
  '+191',
  '1,240 ',
  '+5',
  '12,829',
  '+200',
  '4,913',
  '182',
  '986',
  '64',
  '421,451',
  '21,895',
  '19,248,434 ',
  'Europe',
  '1,01415,52346'],
 ['38',
  'Israel',
  '16,887',
  '+15',
  '284 ',
  '14,727',
  '+48',
  '1,876',
  '37',
  '1,836',
  '31',
  '565,311',
  '61,463',
  '9,197,590 ',
  'Asia',
  '54532,38616'],
 ['39',
  'Japan',
  '16,683',
  '867 ',
  '14,147',
  '1,669',
  '136',
  '132',
  '7',
  '281,293',
  '2,223',
  '126,509,583 ',
  'Asia',
  '7,583145,916450'],
 ['40',
  'Austria',
  '16,655',
  '+27',
  '668 ',
  '15,347',
  '+61',
  '640',
  '25',
  '1,850',
  '74',
  '434,302',
  '48,246',
  '9,001,768 ',
  'Europe',
  '54013,47621'],
 ['41',
  'Dominican Republic',
  '16,068',
  '485 ',
  '8,952',
  '6,631',
  '123',
  '1,483',
  '45',
  '74,612',
  '6,884',
  '10,837,859 ',
  'North America',
  '67422,346145'],
 ['42',
  'Philippines',
  '15,588',
  '921 ',
  '3,598',
  '11,069',
  '81',
  '142',
  '8',
  '323,819',
  '2,959',
  '109,443,743 ',
  'Asia',
  '7,021118,831338'],
 ['43',
  'Argentina',
  '14,702',
  '508 ',
  '4,617',
  '9,577',
  '171',
  '326',
  '11',
  '145,081',
  '3,213',
  '45,157,642 ',
  'South America',
  '3,07288,893311'],
 ['44',
  'Afghanistan',
  '13,659',
  '+623',
  '246 ',
  '+11',
  '1,259',
  '+50',
  '12,154',
  '19',
  '352',
  '6',
  '35,923',
  '925',
  '38,841,361 ',
  'Asia',
  '2,844157,8921,081'],
 ['45',
  'Panama',
  '12,131',
  '320 ',
  '7,379',
  '4,432',
  '72',
  '2,816',
  '74',
  '63,202',
  '14,670',
  '4,308,282 ',
  'North America',
  '35513,46368'],
 ['46',
  'Denmark',
  '11,593',
  '+81',
  '568 ',
  '10,240',
  '+60',
  '785',
  '18',
  '2,002',
  '98',
  '606,574',
  '104,755',
  '5,790,388 ',
  'Europe',
  '49910,19410'],
 ['47',
  'S. Korea',
  '11,402',
  '+58',
  '269 ',
  '10,363',
  '+23',
  '770',
  '15',
  '222',
  '5',
  '885,120',
  '17,265',
  '51,265,321 ',
  'Asia',
  '4,496190,57758'],
 ['48',
  'Serbia',
  '11,354',
  '+54',
  '242 ',
  '+1',
  '6,524',
  '+86',
  '4,588',
  '8',
  '1,299',
  '28',
  '239,234',
  '27,371',
  '8,740,364 ',
  'Europe',
  '77036,11737'],
 ['49',
  'Bahrain',
  '10,352',
  '+300',
  '15 ',
  '5,491',
  '+72',
  '4,846',
  '9',
  '6,106',
  '9',
  '302,640',
  '178,518',
  '1,695,292 ',
  'Asia',
  '164113,0196'],
 ['50',
  'Kazakhstan',
  '9,932',
  '+356',
  '37 ',
  '5,011',
  '+111',
  '4,884',
  '62',
  '530',
  '2',
  '761,727',
  '40,613',
  '18,755,722 ',
  'Asia',
  '1,888506,91125'],
 ['51',
  'Oman',
  '9,820',
  '+811',
  '40 ',
  '2,396',
  '+219',
  '7,384',
  '31',
  '1,928',
  '8',
  '72,000',
  '14,136',
  '5,093,528 ',
  'Asia',
  '519127,33871'],
 ['52',
  'Czechia',
  '9,143',
  '+3',
  '319 ',
  '6,464',
  '+4',
  '2,360',
  '19',
  '854',
  '30',
  '430,564',
  '40,212',
  '10,707,231 ',
  'Europe',
  '1,17133,56525'],
 ['53',
  'Algeria',
  '8,997',
  '630 ',
  '5,277',
  '3,090',
  '32',
  '206',
  '14',
  '43,774,437 ',
  'Africa',
  '4,86569,483'],
 ['54',
  'Nigeria',
  '8,915',
  '259 ',
  '2,592',
  '6,064',
  '7',
  '43',
  '1',
  '58,726',
  '286',
  '205,626,178 ',
  'Africa',
  '23,065793,9233,501'],
 ['55',
  'Armenia',
  '8,676',
  '+460',
  '120 ',
  '+7',
  '3,297',
  '+10',
  '5,259',
  '10',
  '2,928',
  '41',
  '56,042',
  '18,916',
  '2,962,755 ',
  'Asia',
  '34124,69053'],
 ['56',
  'Norway',
  '8,411',
  '236 ',
  '7,727',
  '448',
  '8',
  '1,553',
  '44',
  '245,352',
  '45,290',
  '5,417,374 ',
  'Europe',
  '64422,95522'],
 ['57',
  'Bolivia',
  '8,387',
  '+619',
  '293 ',
  '+13',
  '738',
  '+49',
  '7,356',
  '3',
  '719',
  '25',
  '22,294',
  '1,912',
  '11,657,999 ',
  'South America',
  '1,39039,788523'],
 ['58',
  'Malaysia',
  '7,732',
  '+103',
  '115 ',
  '6,235',
  '+66',
  '1,382',
  '8',
  '239',
  '4',
  '519,944',
  '16,084',
  '32,327,063 ',
  'Asia',
  '4,181281,10562'],
 ['59',
  'Moldova',
  '7,725',
  '282 ',
  '4,123',
  '3,320',
  '256',
  '1,915',
  '70',
  '40,565',
  '10,054',
  '4,034,769 ',
  'Europe',
  '52214,30899'],
 ['60',
  'Morocco',
  '7,697',
  '+54',
  '202 ',
  '5,223',
  '+28',
  '2,272',
  '1',
  '209',
  '5',
  '185,866',
  '5,041',
  '36,869,708 ',
  'Africa',
  '4,790182,523198'],
 ['61',
  'Ghana',
  '7,616',
  '+313',
  '34 ',
  '2,421',
  '+9',
  '5,161',
  '17',
  '246',
  '1',
  '208,328',
  '6,718',
  '31,009,181 ',
  'Africa',
  '4,072912,035149'],
 ['62',
  'Australia',
  '7,173',
  '+23',
  '103 ',
  '6,582',
  '+2',
  '488',
  '4',
  '282',
  '4',
  '1,397,622',
  '54,868',
  '25,472,297 ',
  'Australia/Oceania',
  '3,551247,30418'],
 ['63',
  'Finland',
  '6,776',
  '+33',
  '314  ',
  '+1',
  '5,500',
  '962',
  '10',
  '1,223',
  '57',
  '179,400',
  '32,383',
  '5,539,963 ',
  'Europe',
  '81817,64331'],
 ['64',
  'Iraq',
  '5,457',
  '179 ',
  '2,971',
  '2,307',
  '41',
  '136',
  '4',
  '211,485',
  '5,270',
  '40,132,981 ',
  'Asia',
  '7,354224,207190'],
 ['65',
  'Cameroon',
  '5,436',
  '175 ',
  '1,996',
  '3,265',
  '28',
  '205',
  '7',
  '26,479,422 ',
  'Africa',
  '4,871151,311'],
 ['66',
  'Azerbaijan',
  '4,759',
  '56 ',
  '3,022',
  '1,681',
  '42',
  '470',
  '6',
  '284,669',
  '28,099',
  '10,130,782 ',
  'Asia',
  '2,129180,90736'],
 ['67',
  'Honduras',
  '4,752',
  '+112',
  '196 ',
  '+2',
  '519',
  '+13',
  '4,037',
  '13',
  '481',
  '20',
  '14,790',
  '1,496',
  '9,889,552 ',
  'North America',
  '2,08150,457669'],
 ['68',
  'Guatemala',
  '4,348',
  '+203',
  '80 ',
  '+12',
  '565',
  '+72',
  '3,703',
  '5',
  '243',
  '4',
  '31,427',
  '1,757',
  '17,883,425 ',
  'North America',
  '4,113223,543569'],
 ['69',
  'Sudan',
  '4,346',
  '195 ',
  '749',
  '3,402',
  '99',
  '4',
  '401',
  '9',
  '43,747,206 ',
  'Africa',
  '10,066224,345109,095'],
 ['70',
  'Luxembourg',
  '4,008',
  '110 ',
  '3,803',
  '95',
  '4',
  '6,413',
  '176',
  '71,098',
  '113,756',
  '625,003 ',
  'Europe',
  '1565,6829'],
 ['71',
  'Hungary',
  '3,841',
  '+25',
  '517 ',
  '+8',
  '2,024',
  '+28',
  '1,300',
  '24',
  '398',
  '54',
  '180,152',
  '18,645',
  '9,662,456 ',
  'Europe',
  '2,51618,68954'],
 ['72',
  'Tajikistan',
  '3,563',
  '47 ',
  '1,674',
  '1,842',
  '374',
  '5',
  '9,516,398 ',
  'Asia',
  '2,671202,477'],
 ['73',
  'Guinea',
  '3,553',
  '22 ',
  '1,950',
  '1,581',
  '24',
  '271',
  '2',
  '14,407',
  '1,100',
  '13,096,527 ',
  'Africa',
  '3,686595,297909'],
 ['74',
  'Uzbekistan',
  '3,468',
  '+24',
  '14 ',
  '2,723',
  '+29',
  '731',
  '7',
  '104',
  '0.4',
  '460,000',
  '13,763',
  '33,423,219 ',
  'Asia',
  '9,6382,387,37373'],
 ['75',
  'Senegal',
  '3,429',
  '+81',
  '41 ',
  '+2',
  '1,738',
  '+52',
  '1,650',
  '18',
  '205',
  '2',
  '39,499',
  '2,365',
  '16,699,197 ',
  'Africa',
  '4,870407,297423'],
 ['76',
  'Thailand',
  '3,076',
  '+11',
  '57 ',
  '2,945',
  '74',
  '59',
  '44',
  '0.8',
  '375,453',
  '5,380',
  '69,784,490 ',
  'Asia',
  '22,6871,224,289186'],
 ['77',
  'Djibouti',
  '2,914',
  '20 ',
  '1,241',
  '1,653',
  '2,953',
  '20',
  '25,257',
  '25,599',
  '986,638 ',
  'Africa',
  '33949,33239'],
 ['78',
  'Greece',
  '2,906',
  '175 ',
  '1,374',
  '1,357',
  '16',
  '279',
  '17',
  '170,467',
  '16,348',
  '10,427,362 ',
  'Europe',
  '3,58859,58561'],
 ['79',
  'DRC',
  '2,833',
  '+173',
  '69 ',
  '400',
  '+19',
  '2,364',
  '32',
  '0.8',
  '89,279,074 ',
  'Africa',
  '31,5141,293,900'],
 ['80',
  'Ivory Coast',
  '2,641',
  '32 ',
  '1,326',
  '1,283',
  '100',
  '1',
  '26,021',
  '989',
  '26,312,643 ',
  'Africa',
  '9,963822,2701,011'],
 ['81',
  'Bosnia and Herzegovina',
  '2,485',
  '+23',
  '153 ',
  '1,803',
  '+22',
  '529',
  '4',
  '757',
  '47',
  '63,596',
  '19,374',
  '3,282,532 ',
  'Europe',
  '1,32121,45452'],
 ['82',
  'Bulgaria',
  '2,485',
  '+8',
  '136 ',
  '+2',
  '1,016',
  '+51',
  '1,333',
  '22',
  '357',
  '20',
  '79,389',
  '11,418',
  '6,952,801 ',
  'Europe',
  '2,79851,12488'],
 ['83',
  'Gabon',
  '2,431',
  '14 ',
  '668',
  '1,749',
  '15',
  '1,095',
  '6',
  '12,669',
  '5,705',
  '2,220,492 ',
  'Africa',
  '913158,607175'],
 ['84',
  'El Salvador',
  '2,278',
  '+84',
  '42 ',
  '+3',
  '1,015',
  '+13',
  '1,221',
  '30',
  '351',
  '6',
  '84,650',
  '13,057',
  '6,483,267 ',
  'North America',
  '2,846154,36477'],
 ['85',
  'Croatia',
  '2,245',
  '103 ',
  '+1',
  '2,059',
  '+8',
  '83',
  '4',
  '547',
  '25',
  '65,509',
  '15,949',
  '4,107,393 ',
  'Europe',
  '1,83039,87863'],
 ['86',
  'North Macedonia',
  '2,129',
  '+52',
  '126 ',
  '+5',
  '1,516',
  '+30',
  '487',
  '21',
  '1,022',
  '60',
  '27,684',
  '13,288',
  '2,083,381 ',
  'Europe',
  '97916,53575'],
 ['87',
  'Cuba',
  '1,983',
  '82 ',
  '1,734',
  '167',
  '2',
  '175',
  '7',
  '99,745',
  '8,806',
  '11,327,216 ',
  'North America',
  '5,712138,137114'],
 ['88',
  'Estonia',
  '1,859',
  '+8',
  '67 ',
  '+1',
  '1,610',
  '+36',
  '182',
  '1,401',
  '51',
  '81,719',
  '61,607',
  '1,326,457 ',
  'Europe',
  '71419,79816'],
 ['89',
  'Somalia',
  '1,828',
  '72 ',
  '310',
  '1,446',
  '2',
  '115',
  '5',
  '15,847,882 ',
  'Africa',
  '8,670220,109'],
 ['90',
  'Iceland',
  '1,805',
  '10 ',
  '1,794',
  '+2',
  '1',
  '5,293',
  '29',
  '60,491',
  '177,371',
  '341,043 ',
  'Europe',
  '18934,1046'],
 ['91',
  'Mayotte',
  '1,670',
  '21 ',
  '1,315',
  '334',
  '10',
  '6,136',
  '77',
  '5,200',
  '19,107',
  '272,156 ',
  'Africa',
  '16312,96052'],
 ['92',
  'Lithuania',
  '1,662',
  '+6',
  '68 ',
  '1,216',
  '+23',
  '378',
  '17',
  '610',
  '25',
  '294,091',
  '107,910',
  '2,725,331 ',
  'Europe',
  '1,64040,0789'],
 ['93',
  'Kyrgyzstan',
  '1,662',
  '+68',
  '16 ',
  '1,088',
  '+22',
  '558',
  '4',
  '255',
  '2',
  '109,521',
  '16,813',
  '6,513,873 ',
  'Asia',
  '3,919407,11759'],
 ['94',
  'Kenya',
  '1,618',
  '58 ',
  '421',
  '1,139',
  '7',
  '30',
  '1',
  '70,172',
  '1,308',
  '53,654,106 ',
  'Africa',
  '33,161925,071765'],
 ['95',
  'Sri Lanka',
  '1,530',
  '10 ',
  '754',
  '+9',
  '766',
  '1',
  '71',
  '0.5',
  '60,878',
  '2,844',
  '21,405,231 ',
  'Asia',
  '13,9902,140,523352'],
 ['96',
  'Slovakia',
  '1,520',
  '28 ',
  '1,338',
  '+6',
  '154',
  '278',
  '5',
  '167,562',
  '30,692',
  '5,459,411 ',
  'Europe',
  '3,592194,97933'],
 ['97',
  'Maldives',
  '1,513',
  '5 ',
  '197',
  '1,311',
  '9',
  '2,804',
  '9',
  '11,775',
  '21,821',
  '539,625 ',
  'Asia',
  '357107,92546'],
 ['98',
  'New Zealand',
  '1,504',
  '22 ',
  '1,481',
  '+7',
  '1',
  '301',
  '4',
  '275,852',
  '55,147',
  '5,002,100 ',
  'Australia/Oceania',
  '3,326227,36818'],
 ['99',
  'Slovenia',
  '1,473',
  '108 ',
  '1,357',
  '+1',
  '8',
  '2',
  '709',
  '52',
  '79,284',
  '38,137',
  '2,078,913 ',
  'Europe',
  '1,41119,24926'],
 ['100',
  'Haiti',
  '1,443',
  '+123',
  '35 ',
  '+1',
  '22',
  '1,386',
  '127',
  '3',
  '3,475',
  '305',
  '11,389,523 ',
  'North America',
  '7,893325,4153,278'],
 ['101',
  'Venezuela',
  '1,325',
  '11 ',
  '302',
  '1,012',
  '4',
  '47',
  '0.4',
  '897,695',
  '31,561',
  '28,442,842 ',
  'South America',
  '21,4662,585,71332'],
 ['102',
  'Equatorial Guinea',
  '1,306',
  '+263',
  '12 ',
  '200',
  '+35',
  '1,094',
  '934',
  '9',
  '854',
  '611',
  '1,398,140 ',
  'Africa',
  '1,071116,5121,637'],
 ['103',
  'Nepal',
  '1,212',
  '+170',
  '6 ',
  '+1',
  '206',
  '+19',
  '1,000',
  '42',
  '0.2',
  '169,632',
  '5,832',
  '29,086,128 ',
  'Asia',
  '23,9984,847,688171'],
 ['104',
  'Guinea-Bissau',
  '1,195',
  '8 ',
  '42',
  '1,145',
  '609',
  '4',
  '1,500',
  '764',
  '1,963,357 ',
  'Africa',
  '1,643245,4201,309'],
 ['105',
  'Mali',
  '1,194',
  '72 ',
  '652',
  '470',
  '59',
  '4',
  '3,483',
  '173',
  '20,190,889 ',
  'Africa',
  '16,910280,4295,797'],
 ['106',
  'Lebanon',
  '1,172',
  '+4',
  '26 ',
  '705',
  '+6',
  '441',
  '7',
  '172',
  '4',
  '80,239',
  '11,751',
  '6,828,038 ',
  'Asia',
  '5,826262,61785'],
 ['107',
  'Albania',
  '1,099',
  '+23',
  '33 ',
  '851',
  '+28',
  '215',
  '5',
  '382',
  '11',
  '14,269',
  '4,958',
  '2,878,069 ',

In [ ]:
colnames = rows[0]
data = rows[1:]

In [ ]:
import pandas as pd
df = pd.DataFrame(data, columns=colnames)
df